# Stock Price Prediction using Machine Learning

## Notebook 2: Data Preprocessing & Feature Engineering

### Objective
Prepare the raw stock data by creating meaningful features that improve the performance of the machine learning model.

In [1]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

load the dataset

In [2]:
stock_data = pd.read_csv(
    "../data/apple_stock.csv",
    index_col=0,
    parse_dates=True
)

stock_data.head()

                Close       High        Low       Open     Volume
Date
2020-01-02  72.333885  72.394093  71.091191  71.344062  135480400
2020-01-03  71.630638  72.389257  71.406666  71.563205  146322800
2020-01-06  72.201393  72.239927  70.503531  70.753999  118387200
2020-01-07  71.861839  72.466322  71.642681  72.211041  108872000
2020-01-08  73.017845  73.318885  71.565629  71.565629  132079200

In [3]:
stock_data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1507 entries, 2020-01-02 to 2025-12-30
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   1507 non-null   float64
 1   High    1507 non-null   float64
 2   Low     1507 non-null   float64
 3   Open    1507 non-null   float64
 4   Volume  1507 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 70.6 KB

In [4]:
stock_data.head()

                Close       High        Low       Open     Volume
Date
2020-01-02  72.333885  72.394093  71.091191  71.344062  135480400
2020-01-03  71.630638  72.389257  71.406666  71.563205  146322800
2020-01-06  72.201393  72.239927  70.503531  70.753999  118387200
2020-01-07  71.861839  72.466322  71.642681  72.211041  108872000
2020-01-08  73.017845  73.318885  71.565629  71.565629  132079200

Simplify the Column Names

In [5]:
print(stock_data.columns)

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

. Feature Engineering

In [6]:
# Create Lag Features

stock_data["Lag_1"] = stock_data["Close"].shift(1)
stock_data["Lag_2"] = stock_data["Close"].shift(2)
stock_data["Lag_3"] = stock_data["Close"].shift(3)

# Display first 10 rows
stock_data.head(10)

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3
Date,,,,,,,,
2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,NaN,NaN,NaN
2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,72.333885,NaN,NaN
2020-01-06,72.201393,72.239927,70.503531,70.753999,118387200,71.630638,72.333885,NaN
2020-01-07,71.861839,72.466322,71.642681,72.211041,108872000,72.201393,71.630638,72.333885
2020-01-08,73.017845,73.318885,71.565629,71.565629,132079200,71.861839,72.201393,71.630638
2020-01-09,74.568787,74.761449,73.742735,73.993195,170108400,73.017845,71.861839,72.201393
2020-01-10,74.737366,75.300919,74.236439,74.802395,140644800,74.568787,73.017845,71.861839
2020-01-13,76.334068,76.360564,74.934836,75.052848,121532000,74.737366,74.568787,73.017845
2020-01-14,75.303337,76.481009,75.180518,76.271486,161954400,76.334068,74.737366,74.568787
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366

In [7]:
stock_data.head(10)

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3
Date,,,,,,,,
2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,NaN,NaN,NaN
2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,72.333885,NaN,NaN
2020-01-06,72.201393,72.239927,70.503531,70.753999,118387200,71.630638,72.333885,NaN
2020-01-07,71.861839,72.466322,71.642681,72.211041,108872000,72.201393,71.630638,72.333885
2020-01-08,73.017845,73.318885,71.565629,71.565629,132079200,71.861839,72.201393,71.630638
2020-01-09,74.568787,74.761449,73.742735,73.993195,170108400,73.017845,71.861839,72.201393
2020-01-10,74.737366,75.300919,74.236439,74.802395,140644800,74.568787,73.017845,71.861839
2020-01-13,76.334068,76.360564,74.934836,75.052848,121532000,74.737366,74.568787,73.017845
2020-01-14,75.303337,76.481009,75.180518,76.271486,161954400,76.334068,74.737366,74.568787
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366

In [8]:
stock_data.head(10)

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3
Date,,,,,,,,
2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,NaN,NaN,NaN
2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,72.333885,NaN,NaN
2020-01-06,72.201393,72.239927,70.503531,70.753999,118387200,71.630638,72.333885,NaN
2020-01-07,71.861839,72.466322,71.642681,72.211041,108872000,72.201393,71.630638,72.333885
2020-01-08,73.017845,73.318885,71.565629,71.565629,132079200,71.861839,72.201393,71.630638
2020-01-09,74.568787,74.761449,73.742735,73.993195,170108400,73.017845,71.861839,72.201393
2020-01-10,74.737366,75.300919,74.236439,74.802395,140644800,74.568787,73.017845,71.861839
2020-01-13,76.334068,76.360564,74.934836,75.052848,121532000,74.737366,74.568787,73.017845
2020-01-14,75.303337,76.481009,75.180518,76.271486,161954400,76.334068,74.737366,74.568787
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366

In [9]:
stock_data = pd.read_csv(
    "../data/apple_stock.csv",
    index_col=0,
    parse_dates=True
)

stock_data.head()

                Close       High        Low       Open     Volume
Date
2020-01-02  72.333885  72.394093  71.091191  71.344062  135480400
2020-01-03  71.630638  72.389257  71.406666  71.563205  146322800
2020-01-06  72.201393  72.239927  70.503531  70.753999  118387200
2020-01-07  71.861839  72.466322  71.642681  72.211041  108872000
2020-01-08  73.017845  73.318885  71.565629  71.565629  132079200

Create Lag Features

In [10]:
# Create lag features
stock_data["Lag_1"] = stock_data["Close"].shift(1)
stock_data["Lag_2"] = stock_data["Close"].shift(2)
stock_data["Lag_3"] = stock_data["Close"].shift(3)

stock_data.head(10)

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3
Date,,,,,,,,
2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,NaN,NaN,NaN
2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,72.333885,NaN,NaN
2020-01-06,72.201393,72.239927,70.503531,70.753999,118387200,71.630638,72.333885,NaN
2020-01-07,71.861839,72.466322,71.642681,72.211041,108872000,72.201393,71.630638,72.333885
2020-01-08,73.017845,73.318885,71.565629,71.565629,132079200,71.861839,72.201393,71.630638
2020-01-09,74.568787,74.761449,73.742735,73.993195,170108400,73.017845,71.861839,72.201393
2020-01-10,74.737366,75.300919,74.236439,74.802395,140644800,74.568787,73.017845,71.861839
2020-01-13,76.334068,76.360564,74.934836,75.052848,121532000,74.737366,74.568787,73.017845
2020-01-14,75.303337,76.481009,75.180518,76.271486,161954400,76.334068,74.737366,74.568787
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366

Now Let's Create Our First Moving Average

In [11]:
# Create 5-day Moving Average
stock_data["MA_5"] = stock_data["Close"].rolling(window=5).mean()

# Display first 10 rows
stock_data.head(10)

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3,MA_5
Date,,,,,,,,,
2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,NaN,NaN,NaN,NaN
2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,72.333885,NaN,NaN,NaN
2020-01-06,72.201393,72.239927,70.503531,70.753999,118387200,71.630638,72.333885,NaN,NaN
2020-01-07,71.861839,72.466322,71.642681,72.211041,108872000,72.201393,71.630638,72.333885,NaN
2020-01-08,73.017845,73.318885,71.565629,71.565629,132079200,71.861839,72.201393,71.630638,72.209120
2020-01-09,74.568787,74.761449,73.742735,73.993195,170108400,73.017845,71.861839,72.201393,72.656100
2020-01-10,74.737366,75.300919,74.236439,74.802395,140644800,74.568787,73.017845,71.861839,73.277446
2020-01-13,76.334068,76.360564,74.934836,75.052848,121532000,74.737366,74.568787,73.017845,74.103981
2020-01-14,75.303337,76.481009,75.180518,76.271486,161954400,76.334068,74.737366,74.568787,74.792281
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366,75.184834

In [12]:
stock_data["MA_5"] = stock_data["Close"].rolling(window=5).mean()

Create the 5-Day and 10-Day Moving Averages

In [13]:
# Create Moving Averages
stock_data["MA_5"] = stock_data["Close"].rolling(window=5).mean()
stock_data["MA_10"] = stock_data["Close"].rolling(window=10).mean()

# Display the first 15 rows
stock_data.head(15)

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3,MA_5,MA_10
Date,,,,,,,,,,
2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,NaN,NaN,NaN,NaN,NaN
2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,72.333885,NaN,NaN,NaN,NaN
2020-01-06,72.201393,72.239927,70.503531,70.753999,118387200,71.630638,72.333885,NaN,NaN,NaN
2020-01-07,71.861839,72.466322,71.642681,72.211041,108872000,72.201393,71.630638,72.333885,NaN,NaN
2020-01-08,73.017845,73.318885,71.565629,71.565629,132079200,71.861839,72.201393,71.630638,72.209120,NaN
2020-01-09,74.568787,74.761449,73.742735,73.993195,170108400,73.017845,71.861839,72.201393,72.656100,NaN
2020-01-10,74.737366,75.300919,74.236439,74.802395,140644800,74.568787,73.017845,71.861839,73.277446,NaN
2020-01-13,76.334068,76.360564,74.934836,75.052848,121532000,74.737366,74.568787,73.017845,74.103981,NaN
2020-01-14,75.303337,76.481009,75.180518,76.271486,161954400,76.334068,74.737366,74.568787,74.792281,NaN
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366,75.184834,73.696977
2020-01-16,75.919853,76.030641,75.161234,75.522482,108829200,74.980614,75.303337,76.334068,75.455048,74.055574
2020-01-17,76.760353,76.762756,75.862047,76.167901,137816400,75.919853,74.980614,75.303337,75.859645,74.568546
2020-01-21,76.240150,76.830184,76.102875,76.389465,110843200,76.760353,75.919853,74.980614,75.840862,74.972421
2020-01-22,76.512299,77.063798,76.418371,76.724224,101832400,76.240150,76.760353,75.919853,76.082654,75.437467
2020-01-23,76.880775,76.960247,76.018593,76.565286,104472000,76.512299,76.240150,76.760353,76.462686,75.823760

In [14]:
# Create Daily Return feature
stock_data["Daily_Return"] = stock_data["Close"].pct_change()

# Display first 10 rows
stock_data.head(10)

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3,MA_5,MA_10,Daily_Return
Date,,,,,,,,,,,
2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,72.333885,NaN,NaN,NaN,NaN,-0.009722
2020-01-06,72.201393,72.239927,70.503531,70.753999,118387200,71.630638,72.333885,NaN,NaN,NaN,0.007968
2020-01-07,71.861839,72.466322,71.642681,72.211041,108872000,72.201393,71.630638,72.333885,NaN,NaN,-0.004703
2020-01-08,73.017845,73.318885,71.565629,71.565629,132079200,71.861839,72.201393,71.630638,72.209120,NaN,0.016087
2020-01-09,74.568787,74.761449,73.742735,73.993195,170108400,73.017845,71.861839,72.201393,72.656100,NaN,0.021241
2020-01-10,74.737366,75.300919,74.236439,74.802395,140644800,74.568787,73.017845,71.861839,73.277446,NaN,0.002261
2020-01-13,76.334068,76.360564,74.934836,75.052848,121532000,74.737366,74.568787,73.017845,74.103981,NaN,0.021364
2020-01-14,75.303337,76.481009,75.180518,76.271486,161954400,76.334068,74.737366,74.568787,74.792281,NaN,-0.013503
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366,75.184834,73.696977,-0.004286

In [15]:
# Create Daily Return feature
stock_data["Daily_Return"] = stock_data["Close"].pct_change()

# Display the first 10 rows
stock_data.head(10)

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3,MA_5,MA_10,Daily_Return
Date,,,,,,,,,,,
2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,72.333885,NaN,NaN,NaN,NaN,-0.009722
2020-01-06,72.201393,72.239927,70.503531,70.753999,118387200,71.630638,72.333885,NaN,NaN,NaN,0.007968
2020-01-07,71.861839,72.466322,71.642681,72.211041,108872000,72.201393,71.630638,72.333885,NaN,NaN,-0.004703
2020-01-08,73.017845,73.318885,71.565629,71.565629,132079200,71.861839,72.201393,71.630638,72.209120,NaN,0.016087
2020-01-09,74.568787,74.761449,73.742735,73.993195,170108400,73.017845,71.861839,72.201393,72.656100,NaN,0.021241
2020-01-10,74.737366,75.300919,74.236439,74.802395,140644800,74.568787,73.017845,71.861839,73.277446,NaN,0.002261
2020-01-13,76.334068,76.360564,74.934836,75.052848,121532000,74.737366,74.568787,73.017845,74.103981,NaN,0.021364
2020-01-14,75.303337,76.481009,75.180518,76.271486,161954400,76.334068,74.737366,74.568787,74.792281,NaN,-0.013503
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366,75.184834,73.696977,-0.004286

We calculate the standard deviation of the recent daily returns.
Don't worry about the mathematics yet.
Just remember:
Standard deviation tells us how spread out the values are.
Small standard deviation = Stable prices
Large standard deviation = Unstable prices

In [16]:
# Create 5-day Rolling Volatility
stock_data["Volatility_5"] = stock_data["Daily_Return"].rolling(window=5).std()

# Display first 15 rows
stock_data.head(15)

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3,MA_5,MA_10,Daily_Return,Volatility_5
Date,,,,,,,,,,,,
2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,72.333885,NaN,NaN,NaN,NaN,-0.009722,NaN
2020-01-06,72.201393,72.239927,70.503531,70.753999,118387200,71.630638,72.333885,NaN,NaN,NaN,0.007968,NaN
2020-01-07,71.861839,72.466322,71.642681,72.211041,108872000,72.201393,71.630638,72.333885,NaN,NaN,-0.004703,NaN
2020-01-08,73.017845,73.318885,71.565629,71.565629,132079200,71.861839,72.201393,71.630638,72.209120,NaN,0.016087,NaN
2020-01-09,74.568787,74.761449,73.742735,73.993195,170108400,73.017845,71.861839,72.201393,72.656100,NaN,0.021241,0.013224
2020-01-10,74.737366,75.300919,74.236439,74.802395,140644800,74.568787,73.017845,71.861839,73.277446,NaN,0.002261,0.010409
2020-01-13,76.334068,76.360564,74.934836,75.052848,121532000,74.737366,74.568787,73.017845,74.103981,NaN,0.021364,0.011841
2020-01-14,75.303337,76.481009,75.180518,76.271486,161954400,76.334068,74.737366,74.568787,74.792281,NaN,-0.013503,0.015029
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366,75.184834,73.696977,-0.004286,0.015546
2020-01-16,75.919853,76.030641,75.161234,75.522482,108829200,74.980614,75.303337,76.334068,75.455048,74.055574,0.012526,0.013709
2020-01-17,76.760353,76.762756,75.862047,76.167901,137816400,75.919853,74.980614,75.303337,75.859645,74.568546,0.011071,0.014044
2020-01-21,76.240150,76.830184,76.102875,76.389465,110843200,76.760353,75.919853,74.980614,75.840862,74.972421,-0.006777,0.011466
2020-01-22,76.512299,77.063798,76.418371,76.724224,101832400,76.240150,76.760353,75.919853,76.082654,75.437467,0.003570,0.008727
2020-01-23,76.880775,76.960247,76.018593,76.565286,104472000,76.512299,76.240150,76.760353,76.462686,75.823760,0.004816,0.007653

In [17]:
# Create Target Variable (Tomorrow's Close)
stock_data["Target"] = stock_data["Close"].shift(-1)

stock_data.head(10)

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3,MA_5,MA_10,Daily_Return,Volatility_5,Target
Date,,,,,,,,,,,,,
2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.630638
2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,72.333885,NaN,NaN,NaN,NaN,-0.009722,NaN,72.201393
2020-01-06,72.201393,72.239927,70.503531,70.753999,118387200,71.630638,72.333885,NaN,NaN,NaN,0.007968,NaN,71.861839
2020-01-07,71.861839,72.466322,71.642681,72.211041,108872000,72.201393,71.630638,72.333885,NaN,NaN,-0.004703,NaN,73.017845
2020-01-08,73.017845,73.318885,71.565629,71.565629,132079200,71.861839,72.201393,71.630638,72.209120,NaN,0.016087,NaN,74.568787
2020-01-09,74.568787,74.761449,73.742735,73.993195,170108400,73.017845,71.861839,72.201393,72.656100,NaN,0.021241,0.013224,74.737366
2020-01-10,74.737366,75.300919,74.236439,74.802395,140644800,74.568787,73.017845,71.861839,73.277446,NaN,0.002261,0.010409,76.334068
2020-01-13,76.334068,76.360564,74.934836,75.052848,121532000,74.737366,74.568787,73.017845,74.103981,NaN,0.021364,0.011841,75.303337
2020-01-14,75.303337,76.481009,75.180518,76.271486,161954400,76.334068,74.737366,74.568787,74.792281,NaN,-0.013503,0.015029,74.980614
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366,75.184834,73.696977,-0.004286,0.015546,75.919853

In [18]:
# Create Target Variable
stock_data["Target"] = stock_data["Close"].shift(-1)

stock_data.tail()

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3,MA_5,MA_10,Daily_Return,Volatility_5,Target
Date,,,,,,,,,,,,,
2025-12-23,271.854919,271.994674,269.060124,270.337749,29642000,270.467499,273.162506,271.685242,271.701208,273.974976,0.005130,0.007802,273.302216
2025-12-24,273.302216,274.919206,271.695216,271.834940,17910600,271.854919,270.467499,273.162506,272.094476,273.478897,0.005324,0.006567,272.893005
2025-12-26,272.893005,274.859353,272.353998,273.651606,21521800,273.302216,271.854919,270.467499,272.336029,273.016757,-0.001497,0.006703,273.252350
2025-12-29,273.252350,273.851213,271.844961,272.184327,23715200,272.893005,273.302216,271.854919,272.353998,272.565601,0.001317,0.006244,272.573547
2025-12-30,272.573547,273.571693,271.775043,272.304059,22139600,273.252350,272.893005,273.302216,272.775208,272.462790,-0.002484,0.003629,NaN

In [19]:
# Create Target Variable (Tomorrow's Closing Price)
stock_data["Target"] = stock_data["Close"].shift(-1)

stock_data.tail()

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3,MA_5,MA_10,Daily_Return,Volatility_5,Target
Date,,,,,,,,,,,,,
2025-12-23,271.854919,271.994674,269.060124,270.337749,29642000,270.467499,273.162506,271.685242,271.701208,273.974976,0.005130,0.007802,273.302216
2025-12-24,273.302216,274.919206,271.695216,271.834940,17910600,271.854919,270.467499,273.162506,272.094476,273.478897,0.005324,0.006567,272.893005
2025-12-26,272.893005,274.859353,272.353998,273.651606,21521800,273.302216,271.854919,270.467499,272.336029,273.016757,-0.001497,0.006703,273.252350
2025-12-29,273.252350,273.851213,271.844961,272.184327,23715200,272.893005,273.302216,271.854919,272.353998,272.565601,0.001317,0.006244,272.573547
2025-12-30,272.573547,273.571693,271.775043,272.304059,22139600,273.252350,272.893005,273.302216,272.775208,272.462790,-0.002484,0.003629,NaN

In [20]:
# Remove rows with missing values
stock_data = stock_data.dropna()

# Check if there are any missing values left
print(stock_data.isnull().sum())

Close           0
High            0
Low             0
Open            0
Volume          0
Lag_1           0
Lag_2           0
Lag_3           0
MA_5            0
MA_10           0
Daily_Return    0
Volatility_5    0
Target          0
dtype: int64

In [21]:
stock_data.dropna()

,Close,High,Low,Open,Volume,Lag_1,Lag_2,Lag_3,MA_5,MA_10,Daily_Return,Volatility_5,Target
Date,,,,,,,,,,,,,
2020-01-15,74.980614,75.982475,74.549522,75.103440,121923600,75.303337,76.334068,74.737366,75.184834,73.696977,-0.004286,0.015546,75.919853
2020-01-16,75.919853,76.030641,75.161234,75.522482,108829200,74.980614,75.303337,76.334068,75.455048,74.055574,0.012526,0.013709,76.760353
2020-01-17,76.760353,76.762756,75.862047,76.167901,137816400,75.919853,74.980614,75.303337,75.859645,74.568546,0.011071,0.014044,76.240150
2020-01-21,76.240150,76.830184,76.102875,76.389465,110843200,76.760353,75.919853,74.980614,75.840862,74.972421,-0.006777,0.011466,76.512299
2020-01-22,76.512299,77.063798,76.418371,76.724224,101832400,76.240150,76.760353,75.919853,76.082654,75.437467,0.003570,0.008727,76.880775
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-22,270.467499,273.372106,270.008360,272.353978,36571800,273.162506,271.685242,271.335876,272.150372,274.456082,-0.009866,0.007205,271.854919
2025-12-23,271.854919,271.994674,269.060124,270.337749,29642000,270.467499,273.162506,271.685242,271.701208,273.974976,0.005130,0.007802,273.302216
2025-12-24,273.302216,274.919206,271.695216,271.834940,17910600,271.854919,270.467499,273.162506,272.094476,273.478897,0.005324,0.006567,272.893005
2025-12-26,272.893005,274.859353,272.353998,273.651606,21521800,273.302216,271.854919,270.467499,272.336029,273.016757,-0.001497,0.006703,273.252350
2025-12-29,273.252350,273.851213,271.844961,272.184327,23715200,272.893005,273.302216,271.854919,272.353998,272.565601,0.001317,0.006244,272.573547

In [22]:
stock_data = stock_data.dropna()

print(stock_data.isnull().sum())

print(stock_data.shape)

Close           0
High            0
Low             0
Open            0
Volume          0
Lag_1           0
Lag_2           0
Lag_3           0
MA_5            0
MA_10           0
Daily_Return    0
Volatility_5    0
Target          0
dtype: int64
(1497, 13)

In [23]:
stock_data.to_csv("../data/apple_stock_processed.csv")